server:
  port: 0

spring:
  application:
    name: ms-pedidos
  datasource:
    url: jdbc:mysql://localhost/pedidos?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password:
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
      properties: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.init}
